document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title></title>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no\' />");
document.writeln("	<link href=\'css/mui.min.css\' rel=\'stylesheet\' />");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/iconfont.css\'/>");
document.writeln("	<script src=\'js/mui.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		mui.init()");
document.writeln("		mui.plusReady(function(){");
document.writeln("			var pages = [\'main.html\',\'game.html\',\'rank.php\'];");
document.writeln("			var arr=document.getElementsByClassName(\'mui-tab-item\');");
document.writeln("			var styles = {");
document.writeln("				top:\'45px\',");
document.writeln("      	        bottom:\'51px\',");
document.writeln("			};");
document.writeln("			var objs=[];");
document.writeln("			var self = plus.webview.currentWebview();//取到当前的主页窗口");
document.writeln("			for (var i=0;i<arr.length;i++){");
document.writeln("				var sub=plus.webview.create(pages[i],pages[i],styles);");
document.writeln("				objs.push(sub);");
document.writeln("				!function(i){");
document.writeln("					arr[i].addEventListener(\'tap\',function(){");
document.writeln("						for(var j=0;j<objs.length;j++){");
document.writeln("							if(j!=i) objs[j].hide();");
document.writeln("							else objs[j].show();");
document.writeln("						}");
document.writeln("						self.append(objs[i]);");
document.writeln("					})");
document.writeln("				}(i);");
document.writeln("			}");
document.writeln("			//默认触发第0个选项卡得tap事件。");
document.writeln("			mui.trigger(arr[0],\'tap\');");
document.writeln("	    })");
document.writeln("			");
document.writeln("	</script>");
document.writeln("</head>");
document.writeln(" <style type=\'text/css\'>");
document.writeln("    	");
document.writeln("    </style>");
document.writeln("");
document.writeln("<body>");
document.writeln("	<nav class=\'mui-bar mui-bar-tab\'>");
document.writeln("        <label class=\'mui-tab-item mui-active\' style=\"padding-top: 5px;\" onclick=\"window.location.href=\'main.html\'\" id=\'main\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-home\'></span>");
document.writeln("            <span class=\'mui-tab-label\' style=\"padding-left: 18px;\">首页</span>");
document.writeln("        </label>");
document.writeln("        <label class=\'mui-tab-item\' style=\"padding-top: 5px;\" onclick=\"window.location.href=\'game.html\'\" id=\'game\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-game\'></span>");
document.writeln("            <span class=\'mui-tab-label\'>赛事</span>");
document.writeln("        </label>");
document.writeln("        <label class=\'mui-tab-item\' style=\"padding-top: 5px;\" onclick=\"window.location.href=\'rank.php\'\" id=\'player\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-player\'></span>");
document.writeln("            <span class=\'mui-tab-label\'>球员</span>");
document.writeln("        </label>");
document.writeln("    </nav>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");