document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title></title>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no\' />");
document.writeln("	<link href=\'css/mui.min.css\' rel=\'stylesheet\' />");
document.writeln("	 <link rel=\'stylesheet\' type=\'text/css\' href=\'css/iconfont.css\'/>");
document.writeln("	<script src=\'js/mui.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		mui.init()");
document.writeln("	</script>");
document.writeln("</head>");
document.writeln(" <style type=\'text/css\'>");
document.writeln("    	");
document.writeln("    	#class{");
document.writeln("    		width:100%;");
document.writeln("    		background:cornflowerblue;");
document.writeln("    	}");
document.writeln("    	#class a{");
document.writeln("    		display:inline-block;");
document.writeln("    		height:30px;");
document.writeln("    		line-height:30px;");
document.writeln("    		background:cornflowerblue;");
document.writeln("    		color: #000000;");
document.writeln("    		width:19%;");
document.writeln("    		text-align:center;");
document.writeln("    		top:0px;");
document.writeln("    		left:0px;		");
document.writeln("    		margin-top:0px;");
document.writeln("    	}");
document.writeln("    	");
document.writeln("    	");
document.writeln("    </style>");
document.writeln("");
document.writeln("<body>");
document.writeln("	<header class=\'mui-bar mui-bar-nav\'>");
document.writeln("    <h1 class=\'mui-title\' style=\'position:fixed\'>");
document.writeln("        <font size=\'5\'>");
document.writeln("    		<b><i>TennisWorld</i></b>  ");
document.writeln("    	</font></h1>");
document.writeln("    </header>	");
document.writeln("    ");
document.writeln("     <nav class=\'mui-bar mui-bar-tab\'>");
document.writeln("        <a class=\'mui-tab-item mui-active\' href=\'main.html\' id=\'main\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-home\'></span>");
document.writeln("            <span class=\'mui-tab-label\'>首页</span>");
document.writeln("        </a>");
document.writeln("        <a class=\'mui-tab-item mui-active\' href=\'game.html\' id=\'game\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-game\'></span>");
document.writeln("            <span class=\'mui-tab-label\'>赛事</span>");
document.writeln("        </a>");
document.writeln("        <a class=\'mui-tab-item mui-active\' href=\'play.html\' id=\'player\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-player\'></span>");
document.writeln("            <span class=\'mui-tab-label\'>球员</span>");
document.writeln("        </a>");
document.writeln("    </nav>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");