document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title></title>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no\' />");
document.writeln("	<link href=\'css/mui.min.css\' rel=\'stylesheet\' />");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/iconfont.css\'/>");
document.writeln("	<script src=\'js/mui.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		mui.init()");
document.writeln("	</script>");
document.writeln("</head>");
document.writeln(" <style type=\'text/css\'>");
document.writeln("    	");
document.writeln("    </style>");
document.writeln("");
document.writeln("<body>");
document.writeln("	<nav class=\'mui-bar mui-bar-tab\'>");
document.writeln("        <label class=\'mui-tab-item mui-active\' style=\'padding-top: 5px;\' onclick=\"window.location.href=\'main.html\'\" id=\'main\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-home\' style=\'color: #30333F;\'></span>");
document.writeln("            <span class=\'mui-tab-label\' style=\'padding-left: 18px; color: #30333F;\'>首页</span>");
document.writeln("        </label>");
document.writeln("        <label class=\'mui-tab-item\' style=\'padding-top: 5px;\' onclick=\"window.location.href=\'rank.php\'\" id=\'game\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-player\' style=\'color: #30333F;\'></span>");
document.writeln("            <span class=\'mui-tab-label\' style=\'color: #30333F;\'>球员</span>");
document.writeln("        </label>");
document.writeln("        <label class=\'mui-tab-item\' style=\'padding-top: 5px;\' onclick=\"window.location.href=\'player.html\'\" id=\'player\'>");
document.writeln("            <span class=\'mui-icon iconfont icon-game\' style=\'color: #30333F;\'></span>");
document.writeln("            <span class=\'mui-tab-label\' style=\'color: #30333F;\'>个人</span>");
document.writeln("        </label>");
document.writeln("    </nav>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");